06/16/2021 10:00:23 AM INFO autoreload 14580 14900 Watching for file changes with StatReloader
06/20/2021 10:51:42 PM WARNING log 14580 8676 Not Found: /login
06/20/2021 11:10:57 PM ERROR log 14580 3368 Internal Server Error: /chisiamo
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Python39\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Python39\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Python39\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Python39\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python39\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Python39\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python39\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Python39\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python39\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Python39\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Python39\lib\site-packages\django\template\library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "C:\Python39\lib\site-packages\webpack_loader\templatetags\webpack_loader.py", line 12, in render_bundle
    tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
  File "C:\Python39\lib\site-packages\webpack_loader\utils.py", line 62, in get_as_tags
    bundle = _get_bundle(bundle_name, extension, config)
  File "C:\Python39\lib\site-packages\webpack_loader\utils.py", line 40, in _get_bundle
    bundle = get_loader(config).get_bundle(bundle_name)
  File "C:\Python39\lib\site-packages\webpack_loader\loader.py", line 96, in get_bundle
    raise WebpackError(error)
webpack_loader.exceptions.WebpackError: 
            ModuleBuildError in 
            Module build failed (from ./node_modules/eslint-loader/index.js):
Error: ENOENT: no such file or directory, open 'C:\Projects\Anc20\t190701\anctradate\frontIE\anc-app\src\views\chisiamo\ChisiamoBenemerite.vue'
            
